config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:new, :create, :index, :show] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: {minimum:6}, presence: true
  # validates :list_id, uniqueness: {score: :movie_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
  default_scope { order('rating DESC') }


# private

#   def destroy_listings
#     self.listings.each do |listing|
#     listing.destroy
#   end
# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end
  def create
    set_movie
    @bookmark = Bookmark.new(bookmarks_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private
  def bookmarks_params
    params.require(:bookmark).permit(:comment)
  end

  def set_movie
  @movie = Movie.find(params[:bookmark][:movie_id])
  end

  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "add a bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Poster</th>
      <th colspan="3"></th>
    </tr>
  </thead>


<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/26VJNsFVLZauRT6gIYz5B4hXLRD.jpg); height: 900px;">
    Les Nuits de Cabiria (1957)
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/AqlatSuJvfzzGqKHMPpnF4RRGyM.jpg); height: 900px;">
    L'Éclipse (1962)
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fHEKpWlbMr0mXD5MtMpBlvcx3TQ.jpg); height: 900px;">
    Girl, Interrupted (1999)
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fmCJvc6ZpPaeSGS4bgfc3n5rt00.jpg); height: 900px;">
    Talk to Her (2002)
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/86UEvw3t8amtxepQRtBiQHkk954.jpg); height: 900px;">
    The Gentlemen (2019)
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hQ8vLJyws0tAYbBmzpTKbjdNHKI.jpg); height: 900px;">
    A Bigger Splash (2015)
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
  <h1><%= @list.name %></h1>
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <%= link_to 'add a movie', new_list_bookmark_path(@list), class: 'btn btn-flat' %>
      <%= link_to 'detete this list', list_path(@list), method: :delete, class: 'btn btn-cancel', data: { confirm: 'Are you sure you want to delete this list?' } %>
    </div>
  </div>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="d-flex">
      <h3><%= bookmark.movie.title  %></h3> - <h5><%= bookmark.comment %></h5>
    </div>

  <% end %>
</div>